# Generated by Django 2.2.12 on 2020-05-27 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boatclasses', '0001_initial'),
        ('entities', '0003_auto_20190521_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('allow_anonymous_view', models.BooleanField(default=True, verbose_name='Public can view')),
                ('allow_user_view', models.BooleanField(default=True, verbose_name='Signed in user can view')),
                ('allow_member_view', models.BooleanField(default=True)),
                ('allow_user_edit', models.BooleanField(default=False, verbose_name='Signed in user can change')),
                ('allow_member_edit', models.BooleanField(default=False)),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('update_dt', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('creator_username', models.CharField(max_length=50)),
                ('owner_username', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True, verbose_name='Active')),
                ('status_detail', models.CharField(default='active', max_length=50)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=40, unique=True)),
                ('sailnumber', models.CharField(blank=True, max_length=20)),
                ('hullcolor', models.CharField(blank=True, max_length=20)),
                ('make', models.CharField(blank=True, max_length=40)),
                ('model', models.CharField(blank=True, max_length=20)),
                ('rating', models.IntegerField(default=0)),
                ('boatclass', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='boatclasses.Boatclass')),
                ('creator', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boats_boat_creator', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boats_boat_entity', to='entities.Entity')),
                ('owner', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boats_boat_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Boat',
                'verbose_name_plural': 'Boats',
            },
        ),
    ]
