# Generated by Django 2.2.12 on 2020-05-27 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boats', '0001_initial'),
        ('phrfregions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='phrfregion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='phrfregions.Phrfregion'),
        ),
        migrations.AddField(
            model_name='boat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boats', to=settings.AUTH_USER_MODEL),
        ),
    ]
